### PR TITLE
setting up components folder in react

### PR DESCRIPTION
**Pull request by kaiihayes**

### CODE REVIEW

**Comment by AutumnKennedy** [comment]
Hey Kaitlyn, React Expo is already set up. There's no need to try to set it up again. Are you able to fetch the code that's already there?

**Comment by kaiihayes** [comment]
>  Hey, I'm able to see some files but the only files I can use are App.js 

I made a react web app and not the expo. It has a new folder with src, public, etc.

**Comment by kaiihayes** [comment]
Nevermind I deleted this file and I'm gonna start over

**Comment by AutumnKennedy** [comment]
Hmm, do you think it’s better to just focus on the expo app rn bc that’s what we’re showing at OSRP?

**Pull request closed without merging**
